# Usa un'immagine Node.js come base
FROM node:18-alpine AS builder

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Copia i file package.json e package-lock.json (o yarn.lock)
COPY frontend/package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il resto dei file del frontend
COPY frontend/. ./

# Costruisci l'applicazione React
RUN npm run dev

# Usa un'immagine Nginx per servire i file statici
FROM nginx:alpine

# Copia i file di build dall'immagine builder
COPY --from=builder /app/build /usr/share/nginx/html

# Copia il file di configurazione di Nginx (se necessario)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Espone la porta 80
EXPOSE 3000

# Comando per avviare Nginx
CMD ["nginx", "-g", "daemon off;"]